spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true # 콘솔이 아니라 로그로 남기는게 좋습니다. (밑에 logging.level 옵션 활용)
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace # 로그의 JPA 쿼리에서 바인딩된 파라미터까지 확인 가능